### PR TITLE
Add  `build` method and type parameter to template companions

### PR DESCRIPTION
**Pull request by schlamory**
In preparation for courier fixture data generation, this PR adds a `build` method and type parameter to each template companion. These two additions will facilitate pretty fixture syntax like `val my = fixture[MyRecord]`.

In addition to adding a `build` method to each companion type, this PR deprecates all `apply(<data>, conversion: DataConversion)` methods, as these are rarely (if ever?) used outside of generated Courier classes, compete with the more actively used `apply(<list>, <of>, <fields>)` constructor within IDE auto-complete and argument checking. `apply(<data>, conversion: DataConversion)` is removed in a subsequent PR.

### CODE REVIEW

**Comment by saeta** [comment]
@schlamory this looks great! I'll merge tmr & publish a new version. Once https://github.com/coursera/naptime is clear again for new commits, we can upgrade there, and then incorporate it into Coursera. (And then repeat for the subsequent PRs. :-)

**Comment by amory-coursera** [comment]
Totally missed this message. I guess I must not have Githup notifications enabled XP.

**Comment by kchen-coursera** [comment]
🚢

**Review by yifan-coursera — APPROVED** [review]
LGTM

**Comment by schlamory** [comment]
@eboto The build is failing within your typescript generator tests:
```
[error] (typescript-lite-generator-test/test:npmTest) NPM Build Failed
```
Changes in this PR should be totally independent (changes to Scala generators only). Any idea what's causing this failure?

**Comment by eboto** [comment]
@schlamory my assumption would be that this PR's additions to the reference suite break the typescript somehow. Should be able to take a peek in the next day or so...

**Comment by eboto** [comment]
@schlamory FYI i'll be running some experiments in #41 . Master is broken now, so I now expect that some updated dependency versions in package.json borked the tests but I'll be finding out shortly.

**Comment by eboto** [comment]
@schlamory #41 has the fix. Let this be a cautionary tale about under-specifying dependencies =)

Or, if you want, you can just apply the same minimal changes from #41 and i can close that one, to make life easier on the maintainers.

Hopefully that works and sorry for the pain =)

**Comment by amory-coursera** [comment]
Thanks @eboto . We very much appreciate the quick response!

**Pull request merged**
