### PR TITLE
Configure sbt to correctly publish sbt plugin.

### PR DESCRIPTION
**Pull request by saeta**
Previously, the sbt plugin was not being published correctly. With this config
update, the sbt plugin is published to a bintray repository, and is included
into the sbt plugins default bintray meta-repository.

### CODE REVIEW

**Comment by amory-coursera** [comment]
@yifan-coursera can you verify that this is still doing the right thing, or close it if we don't intend to merge?

**Comment by bryankane** [comment]
Oh, this should definitely be merged. I've had a copy of this branch locally that I use for publishing to bintray on each update. I can try to get that one in a mergeable state, unless you want to take ths on, @yifan-coursera

**Comment by amory-coursera** [comment]
Salient changes already merged.

**Comment by nkconnor** [comment]
Is it possible to publish the plugin for Scala 2.12 and latest version of SBT? It seems like only 2.10 is up
https://dl.bintray.com/coursera/sbt-plugins/org.coursera.courier/courier-sbt-plugin/

**Pull request closed without merging**
